name:                learnyouahaskell
version:             0.2.0.0
github:              "erlnow/learnyouahaskell"
license:             BSD3
license-file:        LICENSE
author:              "Eduardo Ramón Lestau"
maintainer:          "erlestau@gmail.com"
copyright:           "(c) 2020-2030 Eduardo Ramón Lestau"

extra-source-files:
- README.md
- ChangeLog.md
- TODO
- LICENSE
# - baby.lhs

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
synopsis:            "Learn You a Haskell for a Greet Good!"
category:            Learn
description:         Please see the README on GitHub at <https://github.com/erlnow/learnyouahaskell#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

executables:
  learnyouahaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnyouahaskell

tests:
  learnyouahaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnyouahaskell
